name: clang-format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format
      uses: NicholasPilotto/action-clang-format@1.4
      with:
        extensions: 'c, h, C, H, cpp, hpp, cc, hh, c++, h++, cxx, hxx'
